### ISSUE TITLE
Won't install.  Field larger than Field Limit

### ISSUE THREAD

**Issue by GIS-user** [nextgis/qgis_geometry_paster#13]
I actually had it installed and it worked for a while but then was giving me errors about the clipboard exceeding the size.  I uninstalled, but now it won't let me install.  

Here is the error message:

Couldn't load plugin 'geometry_paster' due to an error when calling its initGui() method 

_csv.Error: field larger than field limit (131072) 
Traceback (most recent call last):
  File "C:\Users/jas/OSGeo4W/apps/qgis/./python\qgis\utils.py", line 360, in startPlugin
    plugins[packageName].initGui()
  File "C:\Users/jas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geometry_paster\plugin.py", line 101, in initGui
    self._changeCurrentLayerHandle(self.iface.activeLayer())
  File "C:\Users/jas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geometry_paster\plugin.py", line 225, in _changeCurrentLayerHandle
    self._checkPasteAvalability()
  File "C:\Users/jas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geometry_paster\plugin.py", line 242, in _checkPasteAvalability
    if len(self._tryGetFeaturesGeomsFromClipBoard()) == 0:
  File "C:\Users/jas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geometry_paster\plugin.py", line 203, in _tryGetFeaturesGeomsFromClipBoard
    for row in reader:
  File "C:\Users\jas\OSGeo4W\apps\Python39\lib\csv.py", line 111, in __next__
    row = next(self.reader)
_csv.Error: field larger than field limit (131072)

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.20.0-Odense Odense, decaadbb31 

Python Path:
C:/Users/jas/OSGeo4W/apps/qgis/./python
C:/Users/jas/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/jas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/Users/jas/OSGeo4W/apps/qgis/./python/plugins
C:\Users\jas\OSGeo4W\bin\python39.zip
C:\Users\jas\OSGeo4W\apps\Python39\DLLs
C:\Users\jas\OSGeo4W\apps\Python39\lib
C:\Users\jas\OSGeo4W\bin
C:\Users\jas\OSGeo4W\apps\Python39
C:\Users\jas\OSGeo4W\apps\Python39\lib\site-packages
C:\Users\jas\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\Users\jas\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\Users\jas\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/jas/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\jas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
.
C:\Users\jas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs
C:/Users/jas/Documents/maps/CHQ

**Comment by GIS-user** [comment]
Update:  After posting, the plugin installed, but I started getting the errors I got first time around again (note, I used the plugin for several pastes before this error started).

2023-12-05T13:17:20     WARNING    Traceback (most recent call last):
              File "C:\Users/jas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geometry_paster\plugin.py", line 242, in _checkPasteAvalability
              if len(self._tryGetFeaturesGeomsFromClipBoard()) == 0:
              File "C:\Users/jas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geometry_paster\plugin.py", line 203, in _tryGetFeaturesGeomsFromClipBoard
              for row in reader:
              File "C:\Users\jas\OSGeo4W\apps\Python39\lib\csv.py", line 111, in __next__
              row = next(self.reader)
             _csv.Error: field larger than field limit (131072)
             
2023-12-05T13:17:20     WARNING    Traceback (most recent call last):
              File "C:\Users/jas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geometry_paster\plugin.py", line 242, in _checkPasteAvalability
              if len(self._tryGetFeaturesGeomsFromClipBoard()) == 0:
              File "C:\Users/jas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geometry_paster\plugin.py", line 203, in _tryGetFeaturesGeomsFromClipBoard
              for row in reader:
              File "C:\Users\jas\OSGeo4W\apps\Python39\lib\csv.py", line 111, in __next__
              row = next(self.reader)
             _csv.Error: field larger than field limit (131072)

**Comment by simgislab** [comment]
looks like related to this https://github.com/nextgis/qgis_geometry_paster/pull/12

**Comment by ivanbarsukov** [comment]
Fixed in 240c384b35e88070d33055fdf5cf71fb3035861f by getting rid of dependence on csv module

**Comment by ivanbarsukov** [comment]
A fix was released in version 0.3
